settings:
  application:
    env: dev
    envmsg: "谢谢您的参与"
    host: 0.0.0.0
    isinit: false
    logpath: ./temp/logs/log.txt
    name: testApp
    port: 8000
    readtimeout: 1
    writertimeout: 2
  database:
    database: alterCenter
    dbtype: mysql
    host: localhost
    password: dabing12130
    port: 3306
    username: dabing
